# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poilog2 <- function(x, y, my1, my2, sig1, sig2, ro, nrN) {
    .Call('_numbat_poilog2', PACKAGE = 'numbat', x, y, my1, my2, sig1, sig2, ro, nrN)
}

poilog1 <- function(x, my, sig, nrN) {
    .Call('_numbat_poilog1', PACKAGE = 'numbat', x, my, sig, nrN)
}

CgetQ <- function(logQ, children_dict, node_order) {
    .Call('_numbat_CgetQ', PACKAGE = 'numbat', logQ, children_dict, node_order)
}

