# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

allChildrenCPP <- function(orig) {
    .Call('_Numbat_allChildrenCPP', PACKAGE = 'Numbat', orig)
}

cppdbbinom <- function(x, size, alpha, beta, log_prob = FALSE) {
    .Call('_Numbat_cppdbbinom', PACKAGE = 'Numbat', x, size, alpha, beta, log_prob)
}

poilog2 <- function(x, y, my1, my2, sig1, sig2, ro, nrN) {
    .Call('_Numbat_poilog2', PACKAGE = 'Numbat', x, y, my1, my2, sig1, sig2, ro, nrN)
}

poilog1 <- function(x, my, sig, nrN) {
    .Call('_Numbat_poilog1', PACKAGE = 'Numbat', x, my, sig, nrN)
}

logSumExp <- function(x) {
    .Call('_Numbat_logSumExp', PACKAGE = 'Numbat', x)
}

likelihood_allele_compute <- function(obj, logphi, logprob, logPi, n, m) {
    .Call('_Numbat_likelihood_allele_compute', PACKAGE = 'Numbat', obj, logphi, logprob, logPi, n, m)
}

CgetQ <- function(logQ, children_dict, node_order) {
    .Call('_Numbat_CgetQ', PACKAGE = 'Numbat', logQ, children_dict, node_order)
}

